name: "Get Merged PR URL"
description: "Find the merged PR URL associated with the latest commit"
inputs:
  github-token:
    description: "GitHub Token for API requests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Find Associated PR
      id: find-pr
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Extract the commit hash
        COMMIT_SHA=$(git rev-parse HEAD)

        # Use GitHub API to find the PR associated with this commit
        PR_JSON=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/pulls")

        # Extract the PR URL from the response
          PR_URL=$(echo "$PR_JSON" | jq -r '.[0].html_url')
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

    - name: Output PR URL
      shell: bash
      run: |
        echo "The associated PR URL is: ${{ steps.find-pr.outputs.pr_url }}"
