name: Get Merged PR URL

on:
  push:
    branches: [main]

jobs:
  get-pr-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Associated PR URL
        uses: ./.github/actions/get-pr-url
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
