name: Get Merged PR URL

on:
  push:
    branches: [main]

jobs:
  get-pr-url:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Get the Pull Request associated with this push
      - name: Find Associated PR
        id: find-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the commit hash of the push
          COMMIT_SHA=$(git rev-parse HEAD)

          # Use GitHub API to find the PR associated with this commit
          PR_JSON=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/pulls")

          # Extract the PR URL from the response
          PR_URL=$(echo "$PR_JSON" | jq -r '.[0].html_url')
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT

      - name: Output PR URL
        run: |
          echo "The associated PR URL is: ${{ steps.find-pr.outputs.pr_url }}"
